"""Build compact, offline Japanese readings for the fixed dialogue corpus.

Requires Python 3 + pykakasi==2.3.0 and Node on PATH. No dictionary or network
service is shipped to the browser. Review new vocabulary before committing.
"""
import json
import re
import subprocess
from pathlib import Path
from pykakasi import kakasi

ROOT = Path(__file__).resolve().parents[1]
source = r"""
require('./assets/js/data/companion-dialogues.js');
require('./assets/js/data/companion-remarks.js');
const fs = require('node:fs'), vm = require('node:vm');
const loader = fs.readFileSync('assets/js/core/live2d-loader.js', 'utf8');
const originals = vm.runInNewContext('(' + loader.split('var CHARACTER_INTERACTIONS = ')[1].split(';\n  var preferenceStorageKey')[0] + ')');
const lines = new Set();
function collect(value) {
 if (!value || typeof value !== 'object') return;
 if (typeof value.text === 'string') lines.add(value.text);
 Object.values(value).forEach(collect);
}
[CompanionStories.characters, CompanionRemarks, originals].forEach(collect);
process.stdout.write(JSON.stringify([...lines]));
"""
lines = json.loads(subprocess.check_output(["node", "-e", source], cwd=ROOT))
# Proper nouns and context-sensitive readings used in these particular lines.
overrides = {
    "魔理沙": "まりさ", "霊夢": "れいむ", "咲夜": "さくや",
    "美鈴": "めいりん", "紅魔館": "こうまかん", "香霖": "こうりん",
    "霖之助": "りんのすけ", "小鈴": "こすず", "八卦炉": "はっけろ",
    "三妖精": "さんようせい", "上海": "しゃんはい", "蓬莱": "ほうらい",
    "今日": "きょう", "今年": "ことし", "明日": "あした",
    "一体": "いったい", "一曲": "いっきょく", "一つ": "ひとつ",
    "何体": "なんたい", "何度": "なんど", "大抵": "たいてい",
    "やり方": "やりかた", "間だって": "あいだだって", "止める": "とめる",
    "欲し": "ほし", "陽の光": "ひのひかり", "優れた": "すぐれた",
    "通った": "とおった", "妖魔本": "ようまぼん", "来る人": "くるひと",
    "付け所": "つけどころ", "触らない": "さわらない", "触る": "さわる",
    "一針": "ひとはり", "作り甲斐": "つくりがい", "雪の日": "ゆきのひ",
    "菓子の日": "かしのひ", "飾る日": "かざるひ", "結び方": "むすびかた",
    "瓶": "びん", "の分": "のぶん", "観測係": "かんそくがかり",
    "狙い通り": "ねらいどおり", "箒": "ほうき", "小さい": "ちいさい",
    "考え事": "かんがえごと", "淹れる": "いれる", "近づいた分": "ちかづいたぶん",
    "同じ行": "おなじぎょう", "頃合い": "ころあい", "観測値": "かんそくち",
    "並べて": "ならべて",
    "裁ちかけ": "たちかけ", "端切れ": "はぎれ", "裁縫台": "さいほうだい",
    "鋏": "はさみ", "雛壇": "ひなだん", "短冊": "たんざく", "紐": "ひも",
    "穂先": "ほさき", "軋み": "きしみ", "試運転": "しうんてん",
    "消え際": "きえぎわ", "写本": "しゃほん", "索引": "さくいん",
    "頁": "ぺーじ", "栞": "しおり", "背表紙": "せびょうし",
    "挿絵": "さしえ", "同じ巻": "おなじかん",
    "妖夢": "ようむ", "幽々子": "ゆゆこ", "白玉楼": "はくぎょくろう",
    "萃香": "すいか", "鈴奈庵": "すずなあん", "早苗": "さなえ",
    "鈴仙": "れいせん", "永遠亭": "えいえんてい", "天子": "てんし",
    "衣玖": "いく", "半霊": "はんれい",
    "紫の話": "ゆかりのはなし", "紫を相手": "ゆかりをあいて",
    "紫が": "ゆかりが", "文の取材": "あやのしゅざい",
    "文に人形": "あやににんぎょう", "山で文に": "やまであやに",
    "文に載せ": "あやにのせ", "文は速い": "あやははやい",
    "文は答え": "あやはこたえ", "文の新聞": "あやのしんぶん",
    "文にも、その": "あやにも、その", "空の火力": "うつほのかりょく",
    "空の大きな弾": "うつほのおおきなたま", "空には悪い": "うつほにはわるい",
    # Reviewed contextual readings for the expanded dialogue corpus.
    "沸いた": "わいた",
    "見慣れた人": "みなれたひと",
    "気にする人": "きにするひと",
    "描いた人": "えがいたひと",
    "人が来る": "ひとがくる",
    "焼き菓子": "やきがし",
    "雨の日": "あめのひ",
    "いい日": "いいひ",
    "暑い日": "あついひ",
    "明るい日": "あかるいひ",
    "咲いた日": "さいたひ",
    "配る日": "くばるひ",
    "次の日": "つぎのひ",
    "開ける": "あける",
    "床が冷たい": "ゆかがつめたい",
    "床がよく見える": "ゆかがよくみえる",
    "淹れる間に": "いれるあいだに",
    "よそ見してる間に": "よそみしてるあいだに",
    "入って": "はいって",
    "可愛い": "かわいい",
    "馴染ん": "なじん",
    "見せ所": "みせどころ",
    "包み紙": "つつみがみ",
    "縫い方": "ぬいかた",
    "並べ方": "ならべかた",
    "休ませ方": "やすませかた",
    "印をつけて": "しるしをつけて",
    "間が長すぎる": "まがながすぎる",
    "そこの戸": "そこのと",
    "瓶の札": "びんのふだ",
    "札がある": "ふだがある",
    "次が話しやすい": "つぎがはなしやすい",
    "見張って": "みはって",
    "茶の方は": "ちゃのほうは",
    "本の方は": "ほんのほうは",
    "淹れられる": "いれられる",
    "柄の雪": "えのゆき",
    "入る": "はいる",
    "早起きした分": "はやおきしたぶん",
    "眺めている分": "ながめているぶん",
    "分くらい": "ぶんくらい",
    "割った": "わった",
    "頁数": "ぺーじすう",
    "反って": "そって",
    "雪明かり": "ゆきあかり",
    "役立たない": "やくだたない",
    "二通り": "ふたとおり",
    "重ねて": "かさねて",
    "年が変わった": "としがかわった",
    "触られる": "さわられる",
    "止められた": "とめられた",
    "止められる": "とめられる",
    "頷く": "うなずく",
    "通れる": "とおれる",
    "隙が少ない": "すきがすくない",
    "通らない": "とおらない",
    "弾を揃える": "たまをそろえる",
    "鈴仙の弾": "れいせんのたま",
    "別の弾": "べつのたま",
    "小さい弾": "ちいさいたま",
    "後の方": "あとのほう",
    "後から": "あとから",
    "この間の衣装": "このあいだのいしょう",
}
pattern = re.compile("(" + "|".join(map(re.escape, sorted(overrides, key=len, reverse=True))) + ")")
converter = kakasi()
readings = {}
for line in lines:
    tokens = []
    for segment in pattern.split(line):
        if not segment:
            continue
        if segment in overrides:
            tokens.append([segment, overrides[segment]])
        else:
            tokens.extend([item["orig"], item["hira"]] for item in converter.convert(segment))
    assert "".join(token[0] for token in tokens) == line
    readings[line] = tokens
output = ROOT / "assets/js/data/companion-readings.js"
output.write_text(
    "/* Generated by scripts/generate-companion-readings.py; original text → kana. */\n"
    "(function (root) { root.CompanionReadings = {\n"
    + ",\n".join(json.dumps(text, ensure_ascii=False) + ":" + json.dumps(tokens, ensure_ascii=False, separators=(",", ":")) for text, tokens in readings.items())
    + "\n}; })(typeof window === 'undefined' ? globalThis : window);\n",
    encoding="utf-8",
)
print(f"Generated {len(readings)} complete dialogue readings")
