"""Build compact, offline Japanese readings for the fixed dialogue corpus.

Requires Python 3 + pykakasi==2.3.0 and Node on PATH. No dictionary or network
service is shipped to the browser. Review new vocabulary before committing.
"""
import json
import re
import subprocess
from pathlib import Path
from pykakasi import kakasi

ROOT = Path(__file__).resolve().parents[1]
source = r"""
require('./assets/js/data/companion-dialogues.js');
require('./assets/js/data/companion-remarks.js');
const fs = require('node:fs'), vm = require('node:vm');
const loader = fs.readFileSync('assets/js/core/live2d-loader.js', 'utf8');
const originals = vm.runInNewContext('(' + loader.split('var CHARACTER_INTERACTIONS = ')[1].split(';\n  var preferenceStorageKey')[0] + ')');
const lines = new Set();
function collect(value) {
 if (!value || typeof value !== 'object') return;
 if (typeof value.text === 'string') lines.add(value.text);
 Object.values(value).forEach(collect);
}
[CompanionStories.characters, CompanionRemarks, originals].forEach(collect);
process.stdout.write(JSON.stringify([...lines]));
"""
lines = json.loads(subprocess.check_output(["node", "-e", source], cwd=ROOT))
# Proper nouns and context-sensitive readings used in these particular lines.
overrides = {
    "魔理沙": "まりさ", "霊夢": "れいむ", "咲夜": "さくや",
    "美鈴": "めいりん", "紅魔館": "こうまかん", "香霖": "こうりん",
    "霖之助": "りんのすけ", "小鈴": "こすず", "八卦炉": "はっけろ",
    "三妖精": "さんようせい", "上海": "しゃんはい", "蓬莱": "ほうらい",
    "今日": "きょう", "今年": "ことし", "明日": "あした",
    "一体": "いったい", "一曲": "いっきょく", "一つ": "ひとつ",
    "何体": "なんたい", "何度": "なんど", "大抵": "たいてい",
    "やり方": "やりかた", "間だって": "あいだだって", "止める": "とめる",
    "欲し": "ほし", "陽の光": "ひのひかり", "優れた": "すぐれた",
    "通った": "とおった", "妖魔本": "ようまぼん", "来る人": "くるひと",
    "付け所": "つけどころ", "触らない": "さわらない", "触る": "さわる",
    "一針": "ひとはり", "作り甲斐": "つくりがい", "雪の日": "ゆきのひ",
    "菓子の日": "かしのひ", "飾る日": "かざるひ", "結び方": "むすびかた",
    "瓶": "びん", "の分": "のぶん", "観測係": "かんそくがかり",
    "狙い通り": "ねらいどおり", "箒": "ほうき", "小さい": "ちいさい",
    "考え事": "かんがえごと", "淹れる": "いれる", "近づいた分": "ちかづいたぶん",
    "同じ行": "おなじぎょう", "頃合い": "ころあい", "観測値": "かんそくち",
    "並べて": "ならべて",
}
pattern = re.compile("(" + "|".join(map(re.escape, sorted(overrides, key=len, reverse=True))) + ")")
converter = kakasi()
readings = {}
for line in lines:
    tokens = []
    for segment in pattern.split(line):
        if not segment:
            continue
        if segment in overrides:
            tokens.append([segment, overrides[segment]])
        else:
            tokens.extend([item["orig"], item["hira"]] for item in converter.convert(segment))
    assert "".join(token[0] for token in tokens) == line
    readings[line] = tokens
output = ROOT / "assets/js/data/companion-readings.js"
output.write_text(
    "/* Generated by scripts/generate-companion-readings.py; original text → kana. */\n"
    "(function (root) { root.CompanionReadings = {\n"
    + ",\n".join(json.dumps(text, ensure_ascii=False) + ":" + json.dumps(tokens, ensure_ascii=False, separators=(",", ":")) for text, tokens in readings.items())
    + "\n}; })(typeof window === 'undefined' ? globalThis : window);\n",
    encoding="utf-8",
)
print(f"Generated {len(readings)} complete dialogue readings")
